name: caller_workflow
on:
  workflow_dispatch:
    inputs:
      role:
        description: 'role arn'     
        required: true
        type: string
# push:
jobs:
  calling-test-job:
    uses: Suraj-kaul/fresher-trainee---Ec2_instance/.github/workflows/deploy.yml@master
    with:
     role: ${{ inputs.role }}    
    permissions:
     id-token: write
     contents: read
